package io.github.keycloakmcp.domain.error;

public enum ErrorCode {
    REALM_NOT_FOUND,
    CLIENT_NOT_FOUND,
    USER_NOT_FOUND,
    GROUP_NOT_FOUND,
    ROLE_NOT_FOUND,
    KEYCLOAK_UNAVAILABLE,
    AUTHENTICATION_FAILED,
    AUTHORIZATION_FAILED,
    OPENSHIFT_UNAVAILABLE,
    KUBERNETES_UNAVAILABLE,
    INVALID_ARGUMENT,
    UNSUPPORTED_CAPABILITY,
    ASSESSMENT_FAILED,
    EVIDENCE_COLLECTION_FAILED,
    TARGET_NOT_FOUND,
    TARGET_DISABLED,
    TARGET_UNAVAILABLE,
    TARGET_NOT_AUTHORIZED,
    INTERNAL_ERROR
}
